#! /bin/sh
### BEGIN INIT INFO
# Provides: amp-ctrl
# Required-Start: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: amp-ctrl 
# Description:
### END INIT INFO
 
case "$1" in
    start)
        echo "starting amp-ctrl"
        # Starte Programm
        python /dev/hifiberry-amp-ctrl/amp-ctrl.py
        ;;
esac
 
exit 0